[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.71.1"
  HUGO_THEME = "repo"

[[redirects]]
  from = "https://talentdeploy.com.ar"
  to = "https://www.talentdeploy.com.ar"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://talentdeploy.com.ar/"
  to = "https://www.talentdeploy.com.ar"
  status = 301
  force = true
  headers = {X-From = "Netlify"}
